export const NOTE_NAMES = {
  A: 'A',
  A_SHARP: 'A#',
  B: 'B',
  C: 'C',
  C_SHARP: 'C#',
  D: 'D',
  D_SHARP: 'D#',
  E: 'E',
  F: 'F',
  F_SHARP: 'F#',
  G: 'G',
  G_SHARP: 'G#',
}

export const NOTES = [
  {
    name: 'a',
    label: NOTE_NAMES.A,
    positions: [
      { string: 'E1', position: 5 },
      { string: 'A1', position: 0 },
      { string: 'A1', position: 12 },
      { string: 'D1', position: 7 },
      { string: 'G1', position: 2 },
      { string: 'B1', position: 10 },
      { string: 'E2', position: 5 },
    ],
  },
  {
    name: 'a_sharp',
    label: NOTE_NAMES.A_SHARP,
    positions: [
      { string: 'E1', position: 6 },
      { string: 'A1', position: 1 },
      { string: 'D1', position: 8 },
      { string: 'G1', position: 3 },
      { string: 'B1', position: 11 },
      { string: 'E2', position: 6 },
    ],
  },
  {
    name: 'b',
    label: NOTE_NAMES.B,
    positions: [
      { string: 'E1', position: 7 },
      { string: 'A1', position: 2 },
      { string: 'D1', position: 9 },
      { string: 'G1', position: 4 },
      { string: 'B1', position: 0 },
      { string: 'B1', position: 12 },
      { string: 'E2', position: 7 },
    ],
  },
  {
    name: 'c',
    label: NOTE_NAMES.C,
    positions: [
      { string: 'E1', position: 8 },
      { string: 'A1', position: 3 },
      { string: 'D1', position: 10 },
      { string: 'G1', position: 5 },
      { string: 'B1', position: 1 },
      { string: 'E2', position: 8 },
    ],
  },
  {
    name: 'c_sharp',
    label: NOTE_NAMES.C_SHARP,
    positions: [
      { string: 'E1', position: 9 },
      { string: 'A1', position: 4 },
      { string: 'D1', position: 11 },
      { string: 'G1', position: 6 },
      { string: 'B1', position: 2 },
      { string: 'E2', position: 9 },
    ],
  },
  {
    name: 'd',
    label: NOTE_NAMES.D,
    positions: [
      { string: 'E1', position: 10 },
      { string: 'A1', position: 5 },
      { string: 'D1', position: 0 },
      { string: 'D1', position: 12 },
      { string: 'G1', position: 7 },
      { string: 'B1', position: 3 },
      { string: 'E2', position: 10 },
    ],
  },
  {
    name: 'd_sharp',
    label: NOTE_NAMES.D_SHARP,
    positions: [
      { string: 'E1', position: 11 },
      { string: 'A1', position: 6 },
      { string: 'D1', position: 1 },
      { string: 'G1', position: 8 },
      { string: 'B1', position: 4 },
      { string: 'E2', position: 11 },
    ],
  },
  {
    name: 'e',
    label: NOTE_NAMES.E,
    positions: [
      { string: 'E1', position: 0 },
      { string: 'E1', position: 12 },
      { string: 'A1', position: 7 },
      { string: 'D1', position: 2 },
      { string: 'G1', position: 9 },
      { string: 'B1', position: 5 },
      { string: 'E2', position: 0 },
      { string: 'E2', position: 12 },
    ],
  },
  {
    name: 'f',
    label: NOTE_NAMES.F,
    positions: [
      { string: 'E1', position: 1 },
      { string: 'A1', position: 8 },
      { string: 'D1', position: 3 },
      { string: 'G1', position: 10 },
      { string: 'B1', position: 6 },
      { string: 'E2', position: 1 },
    ],
  },
  {
    name: 'f_sharp',
    label: NOTE_NAMES.F_SHARP,
    positions: [
      { string: 'E1', position: 2 },
      { string: 'A1', position: 9 },
      { string: 'D1', position: 4 },
      { string: 'G1', position: 11 },
      { string: 'B1', position: 7 },
      { string: 'E2', position: 2 },
    ],
  },
  {
    name: 'g',
    label: NOTE_NAMES.G,
    positions: [
      { string: 'E1', position: 3 },
      { string: 'A1', position: 10 },
      { string: 'D1', position: 5 },
      { string: 'G1', position: 0 },
      { string: 'G1', position: 12 },
      { string: 'B1', position: 8 },
      { string: 'E2', position: 3 },
    ],
  },
  {
    name: 'g_sharp',
    label: NOTE_NAMES.G_SHARP,
    positions: [
      { string: 'E1', position: 4 },
      { string: 'A1', position: 11 },
      { string: 'D1', position: 6 },
      { string: 'G1', position: 1 },
      { string: 'B1', position: 9 },
      { string: 'E2', position: 4 },
    ],
  },
];
